### Json format
# { name: hello_world,
#     on: [ push],
#     jobs: {

#     }
# }

# name
name: hello_world

# trigger
on:
    push:

# one or more jobs
jobs:
    greetings:
        runs-on: ubuntu-latest
        steps: 
            - id: s00
              run: echo "Current time in Github is $(date)"